### ISSUE TITLE
Broken package

### ISSUE THREAD

**Issue by eugene-kulak** [alecraso/grnhse-api#8]
At this moment the client doesn't work because of a bug in the auth mixin.
Please release the latest master with the fix.

**Comment by io-ma** [comment]
The package works more than well, that auth issue is solved in [#2 ](https://github.com/alecraso/grnhse-api/issues/2)
You just go into your venv inside the lib directory, python, site packages, grnhse/harvest/. You'll find the api.py file. On line 25 change None with " ". 
That will fix it.

**Comment by eugene-kulak** [comment]
@io-ma I'm sorry, but your fix instructions somewhat controversial to the meaning of "works more than well". As of today, the latest version from PyPI doesn't work as-is because of the above issue. Is there any estimation on the next release? We really need it, thanks

**Comment by io-ma** [comment]
@eugene-kulak I am not a maintainer of the package. I just told you how to fix it if you need it to work as soon as possible. 
Because the maintainer might want to add other improvements before a new release. Or even not issue a new release. It's entirely up to him. Maybe they are very busy. Anyway as far as I understood (from what he answered on that issue I linked to), he really did this package because he needed it then chose to share this solution with others as well.
Now you can wait for the new release or do this tiny change that will make it work extremely well, up to you.

**Comment by eugene-kulak** [comment]
@io-ma Thanks, I appreciate your help. 
In fact, I already did monkey-patching to fix this issue in my case. Which is not ideal for maintainability.
Unfortunately, I can't use install from the git as it is not available on every environment.

**Comment by io-ma** [comment]
Ah, so you need it in more places where you won't have access to change it in the venv. Got it. Well in this case, you could:

1. fork a new version, rename it, add the patch , release and add it to pypi and install it from there 
2. offer the maintainer to become a maintainer of the package too and release it yourself after forking and patching it

**Comment by alecraso** [comment]
Hey folks, I'm going release a new minor version with this fix. I was originally planning to include a fix for #9 as well, but I'll go ahead and release this separately to unblock.

**Comment by io-ma** [comment]
Thank you!
